# Generated by Django 4.0.6 on 2022-08-03 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_productos_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='material',
        ),
    ]
